### ISSUE TITLE
Provider is undefined when using restrictToRoles

### ISSUE THREAD

**Issue by marshallswain** [feathersjs-ecosystem/feathers-authentication-hooks#19]
@eikaramba commented on [Tue Jun 13 2017](https://github.com/feathersjs/feathers-authentication/issues/525)

This might be related to https://github.com/feathersjs/feathers-authentication/issues/432, however i'm using feathers-rest.

### Steps to reproduce
server is using these hooks for user model:
```javascript
const auth = require('feathers-authentication').hooks;
const { restrictToOwner,restrictToRoles } = require('feathers-authentication-hooks');

    get: [
      auth.authenticate('jwt'),
      restrictToRoles({
         roles: ['admin'],
         fieldName: 'group',
         idField: 'id',
         ownerField: 'id',
         owner: true
      }),
      custom_method()
    ],
```

client is calling normally with:
`this.api.service('users').get(payload.userId)`

### Expected behavior
`hook.params.provider` should be set to "rest" when checking inside of `custom_method()`

### Actual behavior
provider is undefined. When i comment out the line for restrictToRoles, it works as expected.

### System configuration (latest as of 13.06.2017)
feathers-2.1.2
feathers-rest-1.7.2
feathers-authentication-1.2.4
feathers-authentication-client-0.3.2
feathers-hooks-2.0.1
feathers-commons-0.8.7
feathers-hooks-common-3.5.1

---

@eikaramba commented on [Tue Jun 13 2017](https://github.com/feathersjs/feathers-authentication/issues/525#issuecomment-308162436)

i just saw that i posted this to the wrong repo. i'm very sorry, it is sometimes really confusing with all these repositories. should i move it?

**Comment by eikaramba** [comment]
Of course this issue is because of https://github.com/feathersjs/feathers-authentication-hooks/blob/master/src/restrict-to-roles.js#L73

I kind of get the intention of that line, but it undermines the whole concept of providers. and unfortunaltey i really need to be able to check the provider environment.

Why? one use case is that i do a lot of additional stuff when getting a user. For example i make a lot of aggregations between tables to collect additional infos. Now i don't want to do this for EVERY get call, as every single request already is doing multiple internal GET calls to user because of authentication etc. Stateless REST for the win ;) So i only do those "heavy" operations when it was an external request, not for the internal ones.

**Comment by daffl** [comment]
You could add your own flag, something like `hook.isInternal`, to the hook.

**Comment by eikaramba** [comment]
actually..... yes, that is an idea. It just undermines the whole provider idea, doesn't it? I mean the documentation clearly states that one can use the provider variable for that context. In the meantime i will try this workaround :)

**Comment by eikaramba** [comment]
@daffl forget my previous statement. the solution you proposed does not work unfortunately. Why? Because provider is already undefined when the authentication hook is internally calling the service again. So provider is already undefined from the very beginning of the request.

For now i am switching the ordering when restrictToRoles is called. I try to put it at the very bottom to avoid not being able to distinguish the providers. however i have the feeling that i will experience situations where i cannot avoid it.
